# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(max_length=10)),
                ('mes', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
